# Generated by Django 5.1 on 2025-10-29 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('data_entrega', models.DateTimeField(verbose_name='Data de Entrega')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil__cargo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_entrega', models.FileField(blank=True, null=True, upload_to='entregas/', verbose_name='Arquivo da Entrega')),
                ('texto_entrega', models.TextField(blank=True, verbose_name='Resposta em Texto (Opcional)')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota (0.00 a 100.00)')),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil__cargo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tarefas.tarefa', verbose_name='Tarefa Associada')),
            ],
            options={
                'verbose_name': 'Entrega de Tarefa',
                'verbose_name_plural': 'Entregas de Tarefas',
                'unique_together': {('tarefa', 'aluno')},
            },
        ),
    ]
