# Generated by Django 5.1 on 2025-10-29 22:37

import django.db.models.deletion
import django.utils.timezone
import tarefas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-data_entrega'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_expiracao'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='arquivo_entrega',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='data_submissao',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='texto_entrega',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_entrega',
        ),
        migrations.AddField(
            model_name='entrega',
            name='arquivo',
            field=models.FileField(default=None, upload_to=tarefas.models.user_directory_path, verbose_name='Arquivo de Entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='comentarios_professor',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Entrega'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_expiracao',
            field=models.DateTimeField(default='2025-12-5', verbose_name='Data de Expiração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_entregas', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tarefas.tarefa', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
