# Generated by Django 5.1 on 2025-10-29 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_entrega_options_alter_tarefa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='alunos_especificos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_superuser': False}, related_name='tarefas_especificas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos Específicos'),
        ),
        migrations.CreateModel(
            name='DesignacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_designacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Designação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('aluno', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='professor_designado', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('professor', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_designados', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Designação de Aluno',
                'verbose_name_plural': 'Designações de Alunos',
                'ordering': ['-data_designacao'],
                'unique_together': {('professor', 'aluno')},
            },
        ),
    ]
