# Generated by Django 5.1 on 2025-10-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_alunos_especificos_designacaoaluno'),
    ]

    operations = [
    ]
