# Generated by Django 5.1 on 2025-10-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_adicionar_designacao_e_alunos_especificos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
