# Generated by Django 5.1 on 2025-11-11 14:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_entrega_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedacaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Redação')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Correção'), ('ia_analisada', 'Analisada pela IA'), ('corrigida', 'Corrigida pelo Professor')], default='pendente', max_length=20)),
                ('palavras_count', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='redacoes_entregues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Redação',
                'verbose_name_plural': 'Entregas de Redação',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='RedacaoCorrecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_1', models.IntegerField(help_text='Domínio da modalidade escrita formal', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='C1 - Norma Culta')),
                ('competencia_2', models.IntegerField(help_text='Compreender a proposta e aplicar conceitos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='C2 - Tema/Tipologia')),
                ('competencia_3', models.IntegerField(help_text='Selecionar e organizar informações', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='C3 - Argumentação')),
                ('competencia_4', models.IntegerField(help_text='Conhecimento dos mecanismos linguísticos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='C4 - Coesão')),
                ('competencia_5', models.IntegerField(help_text='Elaborar proposta de intervenção', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='C5 - Proposta')),
                ('comentario_c1', models.TextField(blank=True, verbose_name='Comentário C1')),
                ('comentario_c2', models.TextField(blank=True, verbose_name='Comentário C2')),
                ('comentario_c3', models.TextField(blank=True, verbose_name='Comentário C3')),
                ('comentario_c4', models.TextField(blank=True, verbose_name='Comentário C4')),
                ('comentario_c5', models.TextField(blank=True, verbose_name='Comentário C5')),
                ('comentario_geral', models.TextField(blank=True, verbose_name='Comentário Geral')),
                ('corrigida_por_ia', models.BooleanField(default=False)),
                ('data_correcao', models.DateTimeField(default=django.utils.timezone.now)),
                ('professor', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='correcoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correcao', to='tarefas.redacaoentrega')),
            ],
            options={
                'verbose_name': 'Correção de Redação',
                'verbose_name_plural': 'Correções de Redação',
            },
        ),
        migrations.CreateModel(
            name='RedacaoAnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestao_c1', models.TextField(blank=True)),
                ('sugestao_c2', models.TextField(blank=True)),
                ('sugestao_c3', models.TextField(blank=True)),
                ('sugestao_c4', models.TextField(blank=True)),
                ('sugestao_c5', models.TextField(blank=True)),
                ('nota_ia_c1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('nota_ia_c2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('nota_ia_c3', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('nota_ia_c4', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('nota_ia_c5', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('analise_geral', models.TextField(blank=True)),
                ('data_analise', models.DateTimeField(default=django.utils.timezone.now)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_ia', to='tarefas.redacaoentrega')),
            ],
            options={
                'verbose_name': 'Análise IA',
                'verbose_name_plural': 'Análises IA',
            },
        ),
        migrations.CreateModel(
            name='RedacaoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Tema')),
                ('enunciado', models.TextField(verbose_name='Enunciado Completo')),
                ('textos_apoio', models.TextField(blank=True, verbose_name='Textos de Apoio')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expiracao', models.DateTimeField(verbose_name='Prazo de Entrega')),
                ('palavras_min', models.IntegerField(default=200, verbose_name='Mínimo de Palavras')),
                ('palavras_max', models.IntegerField(default=500, verbose_name='Máximo de Palavras')),
                ('ativo', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='temas_redacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema de Redação',
                'verbose_name_plural': 'Temas de Redação',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.AddField(
            model_name='redacaoentrega',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tarefas.redacaotema'),
        ),
        migrations.AlterUniqueTogether(
            name='redacaoentrega',
            unique_together={('tema', 'aluno')},
        ),
    ]
